### ISSUE TITLE
Torretas

### ISSUE THREAD

**Issue by Matyrela** [Matyrela/GDC-TowerDefence#20]
# Propiedades de torretas
- Daño
- Costo
- Alcance
- Área de impacto (Caso de daño en área)
- Cadencia / Velocidad de ataque / Frecuencia

- [ ] Torreta simple flechas (Ataca a un enemigo fijo hasta que este muera o se aleje)
- [ ] Torreta de bombas (Mucho cooldown, daño en área, mortero)
- [ ] Torreta de aceite caliente (Ralentiza enemigos + daño over time)
- [ ] Torreta de agua (Crea barro, ralentiza más a los enemigos pero no hace daño)
- [ ] Cañón / Rifle (corto alcance mas daño poca cadencia)
- [ ] Torreta de fuego (Daño lineal, dispara 
- [ ] Torreta Lancero (Ataque con perforación limitada en línea recta, potencialmente daño amplificado contra caballería)
- [ ] Torreta Espadachín (o arma grande X, ataque en arco, particularmente útil para colocar sobre salientes en el muro)
- [ ] Torreta Lanzacohetes (zonal o homing multi-target, buen daño, cadencia baja)

**Comment by PedroScheeffer** [comment]
Che les hice esta planilla si pueden rellenar, asi podemos ya tener una idea del balance 
https://correoucuedu-my.sharepoint.com/:x:/g/personal/pedro_scheeffer_correo_ucu_edu_uy/EbhkXqKZjexHkiEPYeKXR38BeMvO4vn75CoW8D7C8smu0w?e=kFUWYY
